#!/bin/sh
#chkconfig: 2345 80 90
#description:autocyserver
SBIN=/cyserver/bin

# Source function library.
. /etc/rc.d/init.d/functions

if ! [ -x $SBIN/cydaemon.pl ] ; then
        echo "ERROR: $SBIN/cydaemon.pl not found"
        exit 0
fi

DAEMON=$SBIN/cydaemon.pl
PIDFILE=/cyserver/logs/cydaemon.pid

RETVAL=0

start() {
        echo -n $"Starting CYSERVER: "
        daemon $DAEMON > /dev/null 
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/cydaemon
        echo
        return $RETVAL
}


stop() {
       
        echo -n $"Shutting down cydaemon.pl: "
        killproc cydaemon.pl
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/cydaemon
        echo
        return $RETVAL
}



restart() {
        stop
	sleep 1
        start
}


case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  *)
        echo "Usage: autocyserver {start|stop|restart}"
        exit 1
esac

exit $?

