//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CunstomInfo", Namespace="http://schemas.datacontract.org/2004/07/SMSWcfService")]
    [System.SerializableAttribute()]
    public partial class CunstomInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Card_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Card_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vip_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Card_id {
            get {
                return this.Card_idField;
            }
            set {
                if ((this.Card_idField.Equals(value) != true)) {
                    this.Card_idField = value;
                    this.RaisePropertyChanged("Card_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Card_type {
            get {
                return this.Card_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.Card_typeField, value) != true)) {
                    this.Card_typeField = value;
                    this.RaisePropertyChanged("Card_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vip_name {
            get {
                return this.Vip_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Vip_nameField, value) != true)) {
                    this.Vip_nameField = value;
                    this.RaisePropertyChanged("Vip_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IJzyService")]
    public interface IJzyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJzyService/getCustom", ReplyAction="http://tempuri.org/IJzyService/getCustomResponse")]
        test.ServiceReference.CunstomInfo getCustom(string telnum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJzyServiceChannel : test.ServiceReference.IJzyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JzyServiceClient : System.ServiceModel.ClientBase<test.ServiceReference.IJzyService>, test.ServiceReference.IJzyService {
        
        public JzyServiceClient() {
        }
        
        public JzyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JzyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JzyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JzyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public test.ServiceReference.CunstomInfo getCustom(string telnum) {
            return base.Channel.getCustom(telnum);
        }
    }
}
