#!/bin/sh
# $Id$
#
# chkconfig: 345 95 20
# description: cyserver daemon
# processname: autocyserver
# pidfile: /cyserver/logs/cydaemon.pid
#


SBIN=/cyserver/bin

# Source function library.
. /etc/rc.d/init.d/functions

if ! [ -x $SBIN/cydaemon.pl ] ; then
        echo "ERROR: $SBIN/cydaemon.pl not found"
        exit 0
fi

# Full path to fri2d.pl
DAEMON=$SBIN/cydaemon.pl
PIDFILE=/cyserver/logs/cydaemon.pid

RETVAL=0

start() {
#	#check exists pid
	if [ -f ${PIDFILE} ]
	  then PID=`cat ${PIDFILE}`
	       if [ "X${PID}" != "X" ]
	       then dpflag=`ps ax|awk '{print $1}'|grep ${PID}`
		    if [ "X${dpflag}" != "X" ]
		    then
	              echo "cydaemon.pl is already running at pid ${dpflag}."
	              exit 1
		    fi
	       fi
	 fi

        # Start daemons.
        echo -n $"Starting CYSERVER: "
        daemon $DAEMON > /dev/null 
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/cydaemon
        echo
        return $RETVAL
}


stop() {
        # Stop daemons.
        echo -n $"Shutting down cydaemon.pl: "
        killproc cydaemon.pl
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/cydaemon
        echo
        return $RETVAL
}



restart() {
        stop
	sleep 1
        start
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  *)
        echo "Usage: autocyserver {start|stop|restart}"
        exit 1
esac

exit $?

